--- 
document: 
  description: |
    Questo documento fornisce indicazioni per installare e usare il tema WordPress del modello di siti web
    per le scuole italiane. Definisce lo scopo del tema, il processo di installazione, i vari content type del sito e le opzioni di personalizzazione.
  name: "Guida del tema WordPress Design Scuole Italia"
  tags: 
    - siti web
    - design
    - scuole 
